### ISSUE TITLE
@TargetMethod в enum

### ISSUE THREAD

**Issue by irasikhin** [RefOrms2017/reforms#4]
Можно если не указана эта аннотация, по умолчанию использовать Enum.name() функцию, так как это ожидаемо.
Почему не ordinal? Потому что обратная функция для name() есть это valueOf, а для ordinal обратной функции нет, поэтому вообще лучше не рекомендовать пользователям использовать эту функцию у себя в коде.

**Comment by reforms** [comment]
Да, пожелание принимается. Добавлена логика определения соответствия между enum и значением в БД по
следующему правилу строго в указанном порядке:
 1) соответствие определяется, если в enum имеются аннотации
@TargetField и/или @TargetMethod. При этом достаточным является только
указание @TargetField или 2х методов с @TargetMethod

 2) Если аннотаций нет, определяется по типу первого параметра в
конструкторе enum. Считаем такой конструктор - конструктором ассоциаций.

 3) Если enum не имеет конструктора для ассоциации, считается что работа
ведется с name самого enum
