### ISSUE TITLE
Как работать с динамическими запросами?

### ISSUE THREAD

**Issue by irasikhin** [RefOrms2017/reforms#7]
Например у нас есть поле для IN запроса, в нем как могут быть данные так и не могут, сейчас если IN поле пустое вылетает ошибка.
То же самое касается следующих ситуаций, мне нужно по определенному флагу вставлять проверку или не вставлять. Как в такой ситуации писать код?

**Comment by reforms** [comment]
Для этого нужно использовать оператор ::

например так SELECT name FROM users WHERE id IN (**::id**)

Соответственно, если параметр ::id будет NULL выражение  **id IN (::id)** будет удалено из запроса
